[package]
name = "rc_lib"
version = "0.1.0"
authors = ["Muhammad Khuzaima"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
